version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: framework7
    versions:
    - 6.0.10
    - 6.0.11
    - 6.0.12
    - 6.0.14
    - 6.0.15
    - 6.0.6
    - 6.0.7
    - 6.0.8
  - dependency-name: framework7-icons
    versions:
    - 3.0.1
    - 4.0.0
    - 4.0.1
